export const ENV_KEYS = {
  RECAPTCHA_SITE_KEY: 'NEXT_PUBLIC_RECAPTCHA_SITE_KEY',
  RECAPTCHA_SECRET_KEY: 'RECAPTCHA_SECRET_KEY',
  FIREBASE_EMULATOR: 'NEXT_PUBLIC_USE_FIREBASE_EMULATOR',
} as const;
