import type { RoleKey } from './roles';

export const PAGE_PERMISSIONS = [
  // 基本權限
  {
    id: 'dashboard',
    name: '儀表板',
    description: '查看儀表板',
    path: '/dashboard',
  },
  {
    id: 'profile',
    name: '個人資料',
    description: '管理個人資料',
    path: '/profile',
  },
  // 行事曆功能
  {
    id: 'calendar',
    name: '行事曆',
    description: '查看和管理行事曆',
    path: '/calendar',
  },
  // AI 功能
  {
    id: 'gemini',
    name: 'AI 助手',
    description: '使用 Gemini AI 進行對話和檔案分析',
    path: '/gemini',
  },
  // 封存功能
  {
    id: 'archive',
    name: '封存功能',
    description: '封存功能開關',
    path: '/archive',
  },
  {
    id: 'archive-orders',
    name: '封存訂單',
    description: '查看和管理封存訂單',
    path: '/archive/orders',
  },
  {
    id: 'archive-quotes',
    name: '封存估價單',
    description: '查看和管理封存估價單',
    path: '/archive/quotes',
  },
  {
    id: 'archive-contracts',
    name: '封存合約',
    description: '查看和管理封存合約',
    path: '/archive/contracts',
  },
  {
    id: 'archive-projects',
    name: '封存專案',
    description: '查看和管理封存專案',
    path: '/archive/projects',
  },
  {
    id: 'projects',
    name: '專案管理',
    description: '管理專案相關功能',
    path: '/projects',
  },
  {
    id: 'schedule',
    name: '排程管理',
    description: '管理排程相關功能',
    path: '/schedule',
  },
  {
    id: 'orders',
    name: '訂單管理',
    description: '管理訂單相關功能',
    path: '/orders',
  },
  {
    id: 'quotes',
    name: '報價管理',
    description: '管理報價相關功能',
    path: '/quotes',
  },
  {
    id: 'contracts',
    name: '合約管理',
    description: '管理合約相關功能',
    path: '/contracts',
  },
  {
    id: 'notifications',
    name: '通知管理',
    description: '管理通知相關功能',
    path: '/notifications',
  },
  {
    id: 'send-notification',
    name: '發送通知',
    description: '發送系統通知',
    path: '/send-notification',
  },
  {
    id: 'management',
    name: '系統管理',
    description: '管理系統設置和權限',
    path: '/management',
  },
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, readonly string[]> = {
  guest: ['dashboard', 'profile'],
  temporary: ['dashboard', 'schedule', 'profile', 'calendar'],
  helper: ['dashboard', 'schedule', 'orders', 'profile', 'calendar', 'gemini'],
  user: ['dashboard', 'schedule', 'orders', 'quotes', 'profile', 'calendar', 'gemini'],
  coord: ['dashboard', 'schedule', 'orders', 'quotes', 'contracts', 'profile', 'calendar', 'gemini'],
  safety: ['dashboard', 'schedule', 'orders', 'quotes', 'contracts', 'profile', 'calendar', 'gemini'],
  foreman: ['dashboard', 'schedule', 'orders', 'quotes', 'contracts', 'profile', 'calendar', 'gemini'],
  vendor: ['dashboard', 'schedule', 'orders', 'quotes', 'contracts', 'profile', 'calendar', 'gemini'],
  finance: ['dashboard', 'orders', 'quotes', 'contracts', 'profile', 'calendar', 'gemini'],
  manager: [
    'dashboard',
    'profile',
    'archive',
    'archive-orders',
    'archive-quotes',
    'archive-contracts',
    'archive-projects',
    'projects',
    'schedule',
    'orders',
    'quotes',
    'contracts',
    'notifications',
    'send-notification',
    'management',
    'calendar',
    'gemini'
  ],
  admin: [
    'dashboard',
    'profile',
    'archive',
    'archive-orders',
    'archive-quotes',
    'archive-contracts',
    'archive-projects',
    'projects',
    'schedule',
    'orders',
    'quotes',
    'contracts',
    'notifications',
    'send-notification',
    'management',
    'calendar',
    'gemini'
  ],
  owner: [
    'dashboard',
    'profile',
    'archive',
    'archive-orders',
    'archive-quotes',
    'archive-contracts',
    'archive-projects',
    'projects',
    'schedule',
    'orders',
    'quotes',
    'contracts',
    'notifications',
    'send-notification',
    'management',
    'calendar',
    'gemini'
  ],
}; 