type Env = {
  NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: string;
  GOOGLE_RECAPTCHA_SECRET_KEY: string;
};

export const env: Env = {
  NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY:
    process.env.NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY,
  GOOGLE_RECAPTCHA_SECRET_KEY: process.env.GOOGLE_RECAPTCHA_SECRET_KEY,
};