/**
 * 常數匯出檔案
 * 統一匯出所有專案相關的常數
 */

export {
  PROJECT_STATUS_OPTIONS,
  PROJECT_TYPE_OPTIONS,
  PROJECT_PRIORITY_OPTIONS,
  PROJECT_RISK_LEVEL_OPTIONS,
  PROJECT_HEALTH_LEVEL_OPTIONS,
  PROJECT_PHASE_OPTIONS,
} from './projectConstants';

export {
  STATUS_LABELS,
  STATUS_COLORS,
  STATUS_ICONS,
} from './statusConstants';

export {
  PROJECT_VALIDATION_RULES,
  WORKPACKAGE_VALIDATION_RULES,
  JOURNAL_VALIDATION_RULES,
  ISSUE_VALIDATION_RULES,
  VALIDATION_MESSAGES,
} from './validationRules'; 